services:
  balance_app:
    build:
      context: .
    container_name: balance_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - balance-network

  db:
    image: postgres:15-alpine
    container_name: balance_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - balance-network

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: balance_frontend
  #   restart: unless-stopped
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - balance-network

  nginx:
    image: nginx:1.29.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    depends_on:
      - balance_app
    networks:
      - balance-network

volumes:
  postgres_data:

networks:
  balance-network:
